#!/bin/bash

rootfs=$(swupdate -g)

# select the non-active partition for update
if [ "$rootfs" == '/dev/mmcblk0p2' ];then
	selection="-e stable,copy2"
else
	selection="-e stable,copy1"
fi

# state=`fw_printenv ustate | cut -f 2 -d'='`
# if [ $state == 1 ];then
# 	SWUPDATE_SURICATTA_ARGS="-c 2"
# else
# 	SWUPDATE_SURICATTA_ARGS=" "
# fi

if [ -e /data/etc/swupdate.cfg ];then
	CFGFILE="/data/etc/swupdate.cfg"
else
	CFGFILE="/etc/swupdate.cfg"
fi

export SWUPDATE_ARGS="-H raspberrypi4-64:1.0 ${selection} -f ${CFGFILE}"
