---
server:
  commands:
    systemShutdownCommand: sudo shutdown -h now
    systemRestartCommand: sudo shutdown -r now
    serverRestartCommand: sudo service octoprint restart

# https://docs.octoprint.org/en/master/configuration/config_yaml.html?highlight=logs#config-yaml
folder:
  logs: /var/logs/octoprint
  watched: /var/run/octoprint/watched

system:
  actions:
  - name: Update PrintNanny OS
    action: update_printnanny_os
    command: sudo systemctl restart printnanny-update
    confirm: You are about to update PrintNanny OS. System will reboot.
