# Auto-Generated by cargo-bitbake 0.3.16-alpha.0
#


include printnanny-cli-${PV}.inc
inherit cargo

CARGO_SRC_DIR = "gst"
SUMMARY = "PrintNanny Gstreamer App"
HOMEPAGE = "https://github.com/bitsy-ai/printnanny-cli.git"
LICENSE = "AGPL-3.0-or-later"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include printnanny-gst-${PV}.inc
include printnanny-gst.inc
