---
server:
  commands:
    systemShutdownCommand: sudo shutdown -h now
    systemRestartCommand: sudo shutdown -r now
    serverRestartCommand: sudo systemctl restart octoprint.service

# https://docs.octoprint.org/en/master/configuration/config_yaml.html?highlight=logs#config-yaml
# folder:
#   logs: /var/logs/octoprint
#   watched: /var/run/octoprint/watched

system:
  actions:
    - name: Update PrintNanny OS
      action: update_printnanny_os
      command: sudo systemctl restart printnanny-update
      confirm: You are about to update PrintNanny OS. System will reboot.

events:
  subscriptions:
    - command: sudo systemctl start printnanny-vision.service
      debug: false
      event: plugin_octoprint_nanny_nnstreamer_start
      type: system
      enabled: true
    - command: sudo systemctl stop printnanny-vision.service
      enabled: true
      debug: false
      event: plugin_octoprint_nanny_nnstreamer_stop
      type: system

webcam:
  stream: /printnanny-hls/playlist.m3u8
